#!/bin/bash

cd "$HOME"

echo "Bootstratpping ---------------"

echo "> Init submodules"
yadm submodule update --recursive --init

echo "> Check and install Homebrew"

system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

else
  echo "Not a Darwin System, skipping..."
fi

echo "> Install nightly rust"
rustup install nightly


echo "Bootstrapped -----------------"
